### ISSUE TITLE
Failed to execute 'querySelectorAll' in older browsers

### ISSUE THREAD

**Issue by d3v1an7** [11ty/is-land#23]
Hey! I'm on v4, and have included `is-land` in my bundle with a `import '@11ty/is-land';`.
The bundle target is `es2017`, as we seem to have quite a few older devices in our audience.

I've noticed the following error in Sentry, which points [at this line](https://github.com/11ty/is-land/blob/43bd04d204b56a377f65d068c93ef35dbd3ddf52/is-land.js#L100):
```
SyntaxError: Failed to execute 'querySelectorAll' on 'Element': ':not(is-land,:defined,[defer-hydration])' is not a valid selector.
  at {_Island#2}.forceFallback(../../node_modules/@11ty/is-land/is-land.js:100:40)
  at {_Island#2}.connectedCallback(../../node_modules/@11ty/is-land/is-land.js:126:12)
  at app_default(../../node_modules/@11ty/is-land/is-land.js:328:25)
  at <anonymous>(../../src/js/app.js:4:45)
```

Only happens in relatively old browsers -- Chrome Mobile 39 through 60. Seems like folks on older phones?

I'm not sure what the best way to handle this might be for the lib as a whole? But for my very specific use case, I'd prefer the default in this instance to be 'just load the things right now', as if `is-land` wasn't being used at all -- I hope that makes sense!

**Comment by d3v1an7** [comment]
I just noticed #21, which _might_ already address this :)

**Comment by vanarok** [comment]
It looks like the maintainers have focused on developing the 11ty core instead of plugins

**Comment by zachleat** [comment]
Completed an extensive browser support review, here are the unique items in this package:

// computed property name Chrome 47 Firefox 34 Safari 8
// :not() selector list Chrome 88*** Firefox 84*** Safari 9
// :is() Chrome 88*** Firefox 78 Safari 14***
// spread Chrome 46 Firefox 16 Safari 8
// replaceWith Chrome 54 Firefox 49 Safari 10
// isConnected Chrome 51 Firefox 49 Safari 10
// once Chrome 55 Firefox 50 Safari 10

#21 will ship with v5.0.0, removing `:not()` selector list and `:is()` requirement which will change the compatibility to Chrome 55+, Firefox 50+, and Safari 10+.

**Comment by zachleat** [comment]
Also added a `replaceWith` cut the mustard feature test requiring Chrome 54 Firefox 49 and Safari 10.

Appreciate y’alls patience here!
